import type { NextPage } from "next";
import Head from "next/head";
import { useRef } from "react";
import Header from "../components/Header";
import Project from "../components/Project";
import Section from "../components/Section";
import SectionTitle from "../components/SectionTitle";
import Skill from "../components/Skill";
import TableRow from "../components/TableRow";
import { projects } from "../Data/Projects";
import { Skills } from "../Data/Skills";
const Home: NextPage = () => {
  const resumeRef = useRef<HTMLDivElement>(null);

  return (
    <>
      <Head>
        <title>My Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        ref={resumeRef}
        className="max-w-3xl mx-2 md:mx-auto my-2 border p-5 shadow-lg"
      >
        <Header resumeRef={resumeRef} />
        <Section>
          <SectionTitle>Objective</SectionTitle>
          <p className=" text-md font-pop">
            I am a passionate front-end web developer. I love to work with
            javascript. Most of the time I work with React.js and Node.js.
          </p>
        </Section>
        <Section>
          <SectionTitle>Skills</SectionTitle>
          <div className="flex flex-wrap gap-2">
            {Skills.map(({ skillName }, i) => (
              <Skill key={i} skillName={skillName} />
            ))}
          </div>
        </Section>
        <Section>
          <SectionTitle>personal projects</SectionTitle>
          <div className="flex flex-col gap-5">
            {projects.map((project) => (
              <Project {...project} key={project.projectId} />
            ))}
          </div>
        </Section>
        <Section>
          <SectionTitle>Education</SectionTitle>
          <table className="w-full">
            <thead>
              <tr className="border text-center">
                <td className="border-r font-medium ">Exam</td>
                <td className="border-r font-medium ">Board</td>
                <td className="border-r font-medium ">Group</td>
                <td className="border-r font-medium ">Year</td>
                <td className="font-medium">Result</td>
              </tr>
            </thead>
            <tbody>
              <TableRow
                examName="SSC"
                board="Dhaka"
                year={2019}
                gpa={4.5}
                group="Science"
              />
              <TableRow
                examName="HSC"
                board="Dhaka"
                year={2021}
                gpa={5.0}
                group="Science"
              />
            </tbody>
          </table>
        </Section>
      </div>
    </>
  );
};

export default Home;
